[package]

name = "piston-music"
version = "0.12.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["piston", "music"]
description = "A high level library for playing music"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/music.git"
homepage = "https://github.com/PistonDevelopers/music"

[lib]

name = "music"
path = "src/lib.rs"

[dependencies]
current = "0.1.1"
sdl2_mixer = "0.22.0"
sdl2 = "0.22.0"

[dev-dependencies]
piston_window = "0.53.0"
