[package]

name = "piston-music"
version = "0.15.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["piston", "music"]
description = "A high level library for playing music"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/music.git"
homepage = "https://github.com/PistonDevelopers/music"

[lib]

name = "music"
path = "src/lib.rs"

[dependencies]
current = "0.1.2"
sdl2_mixer = "0.24.0"
sdl2 = "0.24.0"

[dev-dependencies]
piston_window = "0.54.0"
